name: hello-world
on: push
jobs:
 my-job:
  runs-on: ubuntu-latest
  steps:
    - name: my-step
      run: echo "Hello World!"
    - name: college
      run: echo today's workshop
    - name: assignement
      run: echo maths assignment
    - name: advertisement 
      run: echo pencil
